<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SchoolMgmtSystem.DAL\SchoolMgmtSystem.DAL.csproj" />
    <ProjectReference Include="..\SchoolMgmtSystem.Models\SchoolMgmtSystem.Models.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
